### ISSUE TITLE
Values for HARVEST table ? 

### ISSUE THREAD

**Issue by gkowalski** [PCORnet-DRN-OC/PCORnet-Data-Curation#2]
We have placed an "04" into various columns of the HARVEST table , per the spec , and found them rejected y the query as "Values outside of CDM specifications" ( See attached screen shot for RX_END_DATE_MGMT field ). 
![screen shot 2016-04-01 at 9 04 16 am](https://cloud.githubusercontent.com/assets/617805/14209296/1e97b3aa-f7e9-11e5-9b14-9eb471ac9ba7.png)

We're looking at the "Common Data Model (CDM) Specification, Version 3.0" spec
![screen shot 2016-04-01 at 9 07 50 am](https://cloud.githubusercontent.com/assets/617805/14209355/65580b1e-f7e9-11e5-8fca-d6fa2dca8408.png)

Are we just not reading hte specifications correctly ?

**Comment by rusincovitch** [comment]
Hi @gkowalski - thank you for reporting! I'll check with the team now and plan to have an update for you soon.

**Comment by rusincovitch** [comment]
@gkowalski, this is to confirm that the issue has been confirmed as a bug, with thanks to you for recognizing it and bringing it to our attention!

In the short term, this issue will be managed in the reporting output. A full resolution will be incorporated into the next code package release.
